# Project
version=2.1.1
group=com.mrbysco.durabilitynotifier

# Common
minecraft_version=1.21.1

# NeoForge
neo_version=21.1.170
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.116.0+1.21.1
fabric_loader_version=0.16.14
cloth_config_version=15.0.140
mod_menu_version=11.0.3

# Mod options
mod_name=DurabilityNotifier
mod_author=Mrbysco
mod_id=durabilitynotifier

#Publishing
curseforge_id=277095
modrinth_id=yGpT1GvE

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false