# Project
version=2.3.3
group=com.mrbysco.durabilitynotifier

# Common
minecraft_version=1.21.6

# NeoForge
neo_version=21.6.12-beta
neogradle.subsystems.parchment.minecraftVersion=1.21.5
neogradle.subsystems.parchment.mappingsVersion=2025.06.15
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.127.1+1.21.6
fabric_loader_version=0.16.14
cloth_config_version=19.0.147
mod_menu_version=15.0.0-beta.3

# Mod options
mod_name=DurabilityNotifier
mod_author=Mrbysco
mod_id=durabilitynotifier

#Publishing
curseforge_id=277095
modrinth_id=yGpT1GvE

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false