modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Mrbysco/durability-notifier/issues"
license = "MIT"

[[mods]]
modId = "durabilitynotifier"
version = "${file.jarVersion}"
displayName = "Durability Notifier"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/durability-notifier"
authors = "Mrbysco"
description = '''A minecraft mod that notifies you when your durability gets at a certain percentage'''

[[dependencies.durabilitynotifier]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.21.11,1.22)"
ordering = "NONE"
side = "BOTH"
[[dependencies.durabilitynotifier]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.11.0-beta,)"
ordering = "NONE"
side = "BOTH"